### ISSUE TITLE
Use non-FV when there are no cubes in the mesh

### ISSUE THREAD

**Issue by SoilRos** [lkeegan/spatial-model-editor#153]
Unfortunately, the version with FV and CG is quite slow in `dune-copasi` because one has to check which local operator to use for each integral in the entity. This turns out to be quite expensive due several reasons. I am checking ways to cache the result and to make it faster, but in general, is always better to use the CG traits (`ModelMultiDomainPkDiffusionReactionTraits<...>`) whenever one knows a priori that there won't be cubes in the mesh.

**Comment by lkeegan** [comment]
thanks @SoilRos - I'll change it to use only CG when simulating single compartment models

**Comment by SoilRos** [comment]
> I'll change it to use only CG when simulating single compartment models

Mmm, that's not what I meant. In my comment, I was referring to the multi-compartment case. Maybe this will guide you a bit more:

* Single compartment:
  * Use `ModelPkDiffusionReactionTraits`
    *  `k == 0` will run the finite volume method in any geometry type (be aware that flux correction is not applied in triangles)
    * `k > 0` will run a the continuous Galerkin case. Only available for triangles.
* Multiple compartments:
   * All compartments have same geometry type?
      * Use `ModelMultiDomainPkDiffusionReactionTraits`
        * Same rules a for single compartment case on every compartment
  * Is there a stripe of cuboid elements or compartments with different geometries?
    * Use `ModelMultiDomainP0PkDiffusionReactionTraits`
      * Similar rules as for single compartment but cubes always use finite volume method.

The single compartment case uses a slightly different `ini` file than the multidomain case. (There is no definition of different compartments of course). Take a look at the `dune_copasi_sd.cc` to see how you can get a multicompartment `ini` file running in a "single-compartment" setting. If in doubt, just ask me.

**Comment by lkeegan** [comment]
Thanks for the clarification. Currently in the multi-compartment case we need the cuboid stripes to implement the membrane reactions between the compartments, but once we can specify the membrane reactions as fluxes between compartments of triangles I'll change to using `ModelMultiDomainPkDiffusionReactionTraits` when possible.
