### ISSUE TITLE
DUNE automatic timestep choice

### ISSUE THREAD

**Issue by lkeegan** [lkeegan/spatial-model-editor#196]
todo

- automatic timestep for DUNE
- allow user to adjust relative/absolute error tolerance in GUI
- but default settings should just work (as much as possible)

**Comment by SoilRos** [comment]
For the 1.0 release, the time-stepping will be made by the model directly. But in the middle term, I envisage a that time integration is made outside the model and controlled in detail by the C++ user. Pretty much as how the steppers in [boost odeint](https://www.boost.org/doc/libs/1_74_0/index.html) work.
