### ISSUE TITLE
native file dialogs

### ISSUE THREAD

**Issue by fbergmann** [lkeegan/spatial-model-editor#199]
Trying out the editor, i've noticed that native file dialogs are not being used. Is there a specific reason for this? Looking at the source this is done on purpose by passing `QFileDialog::Option::DontUseNativeDialog` to the file dialog. 

At least it would be nice to have the option to use them.

**Comment by lkeegan** [comment]
@fbergmann this was just done to make CI testing easier, I'll change them back to the default native ones.

**Comment by fbergmann** [comment]
There would be nothing wrong with having this value changed based on preferences / command line options, so that CI testing would still work as intended.
