### ISSUE TITLE
enhancement for setting spatial initialConcentrations: from expressions

### ISSUE THREAD

**Issue by fbergmann** [lkeegan/spatial-model-editor#206]
It would be nice if the expressions could be enhanced to add logical functions. This would be useful to localize expressions to certain parts of the image. For example: 

    (x > 1) && ( x < 2 )

or in function form: 

    and(gt(x,1), lt(x, 2))

would just narrow the values in the range x > 1 and < 2. The idea would be that the boolean expression would be 1 wherever it is true, and 0 otherwise. Support for these is already in libSBML (for converting infix -> math , or evaluating them)

Additional variables would be 'width' and 'height' that would be useful as well in expressions.

**Comment by lkeegan** [comment]
This would be good to support - I'll look into it.
We need to make sure that any such expressions are also correctly interpreted and evaluated by both SymEngine for the editor, and by muParser for DUNE.

**Comment by fbergmann** [comment]
It might not have to be, it would be easy enough to evaluate the expressions once, generating data for each of the positions, just as you do right now when you read in an image. In that case it would be controlled to just the one action. (and you wouldn't have to change your dune parsers)

**Comment by lkeegan** [comment]
Good point! I'll change to using libSBML for evaluating the analytic initial concentration expressions (and elsewhere where possible): <https://github.com/lkeegan/spatial-model-editor/wiki/Math>
