### ISSUE TITLE
reserved variable names in DUNE ini file

### ISSUE THREAD

**Issue by lkeegan** [lkeegan/spatial-model-editor#68]
In the DUNE ini file, diffusion "constant" & initial reactions can be all be functions of space in ini file.

This means that `x`, `y` and also `pi` and `dim` are reserved and should not be used in the equations in the DUNE ini file.

All constants have already been substituted at this point, so the only variables left in the ini file expressions are the species names themselves.

**todo: check when generating DUNE ini file that species names are not one of the following:**

- `x`
- `y`
- `pi`
- `dim`

**Comment by SoilRos** [comment]
The names should also not contain periods `.` as they define sections in the inifile. Preferably only alphanumeric character and underscores (dashes may be interpreted as minus e.g. `cytoplasm-membrane`). I am not sure whether trigonometric functions and other basic functions defined in muparser may also collide. Aditionally, it would be good if you could reserve `t` as well as it may be useful in the future.

**Comment by lkeegan** [comment]
@SoilRos thanks for the info
- the variable names coming from the SBML model are constrained to contain only alphanumeric chars and underscores (p13 http://sbml.org/Special/specifications/sbml-level-3/version-2/core/release-2/sbml-level-3-version-2-release-2-core.pdf)
- I'll use an underscore instead of `-` for the "membrane" compartment names
- I'll add a check for name clashes with `x`,`y`,`t`,`pi`,`dim` and the muparser function names
