### ISSUE TITLE
DUNE visualization

### ISSUE THREAD

**Issue by lkeegan** [lkeegan/spatial-model-editor#78]
we currently have a simple & fast visualization of species concentrations from DUNE:
- average over the three corner values for each triangle
- set the entire triangle to this average value

two better (but slower) alternatives to implement:
- linear interpolation
  - find bounding box of each triangle
  - for each pixel, calculate Baryocentric weight
  - if non-negative, calculate concentration using weights
  - see e.g. https://codeplea.com/triangular-interpolation
- generic any-order solution
  - as above to find points inside triangle
  - but then convert each point to local coordinate in DUNE
  - evaluate DUNE function at this local coordinate

**Comment by SoilRos** [comment]
I don't understand why you want to interpolate the values by yourself. The evaluation method in the grid function already does that job! Is there any particular reason why you want to do this? If you explain me how you get from a concentration to an image in Qt, we could find an optimal way to do it.

**Comment by lkeegan** [comment]
@SoilRos the idea of interpolating in the GUI is to eventually do this using OpenGL or similar, since rendering a triangle is something that can be done very fast by a graphics card, see e.g. https://open.gl/drawing (but this is not at all a priority)

To get from concentration to image, I need a value for the concentration for each pixel in the image, so I was thinking of doing this in two parts:
- identify each pixel with its triangle & local coordinate (this only needs to be done again if the grid is changed):
  - iterate over triangles, get corner vertices
  - convert corner vertices to pixel locations in the image & find bounding box of triangle
  - iterate over pixels in bounding box & calculate Baryocentric weight
  - if non-negative, then pixel is in the triangle
  - rescale pixel location to global coordinate, then convert to local coordinate in DUNE
- use the grid evaluation method to get the concentration at each pixel using the element & local coordinate

Does that make sense?

**Comment by SoilRos** [comment]
Yes that makes sense. Just that you don't need to calculate the Baryocentric weight. To check whether a coordinate is inside you can use the reference element for it:

```c++
auto gf = model.get_grid_function(...);
range(auto&& entity : Dune::elements(gf.getGridView()))
{
  Dune::VectorField<dobule,2> global_pixel_pos = get_pixel_pos(...);
  auto geo = entity.geometry();
  auto ref_el = Dune::referenceElement(geo);
  auto local_pixel_pos = geo.local(global_pixel_pos)
  bool is_inside = ref_el.checkInside(local_pixel_pos);

  if (is_inside)
    do_vey_complicated_stuffs(...);
}
```

If I understand well, that makes possible to plot whatever the grid function is returning at these pixel points.

**Comment by lkeegan** [comment]
@SoilRos thanks! I'll use the `.checkInside` method instead of calculating Barycentric weights.
