### ISSUE TITLE
GUI DUNE integration

### ISSUE THREAD

**Issue by lkeegan** [lkeegan/spatial-model-editor#85]
- currently the GUI generates `.tif` and `.msh` files as input to DUNE.
- this is useful to be able to run DUNE separately, but would be better not to produce these files when running within the GUI
- can avoid generating `.msh` file by providing dune-copasi with the grid directly
  - need to reimplement `dune/copasi/gmsh_reader.hh` without the gmsh bit
- can avoid the `tif` files by providing a grid function for evaluating the initial concentrations
  - need to provide a `vector<shared_ptr<vector<shared_ptr<GF>>>>`
  - first vector contains compartments, second vector contains species
  - see `dune/copasi/pdelab_expression_adapter.hh`
  - note all functions must be defined for the entire mesh (not just the compartment where the species lives)

**Comment by SoilRos** [comment]
>  - can avoid the `tif` files by providing a grid function for evaluating the initial concentrations 

In [this commit](https://gitlab.dune-project.org/copasi/dune-copasi/merge_requests/17/diffs?commit_id=c1e243a98f01a30b5fea5785758d36496122e3cf#7a15aa4b072aebf32e966acfd6ebbdf1a2d69fe3_291_292) I added this functionality. That is, set initial condition for all the species with any class that fulfils the [PDELab grid function concept](https://gitlab.dune-project.org/copasi/dune-copasi/blob/master/dune/copasi/concepts/pdelab.hh#L61).
